web/__init__.py
from flask import Flask, render_template,jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow

app = Flask(__name__)

db = SQLAlchemy()
migrate = Migrate()
marshmallow = Marshmallow()

@app.errorhandler(400)
def _400(e):
    return jsonify(msg="some data are empty"),400

@app.errorhandler(404)
def _404(e):
    return jsonify(msg="page not found"),404

def run():
    from .config import Config,ConfigProd
    
    app.jinja_env.auto_reload = True
    app.config["TEMPLATES_AUTO_RELOAD"] = True
    # change to ConfigProd before deploying
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)
    marshmallow.init_app(app)

    from .routes import bitpy
    from .api import api

    app.register_blueprint(bitpy, url_prefix="/")
    app.register_blueprint(api, url_prefix="/api/v1")
    
    from .model import Link

    return app
    

web/routes.py
from flask import Blueprint,render_template,request,redirect,url_for
from .model import Link
from . import db

bitpy = Blueprint("route", __name__, template_folder="templates")


def get_unique_id():
    import random
    import string

    return "".join(random.choices(string.ascii_lowercase + string.digits, k=4))

@bitpy.route("/",methods=["GET","POST"])
def index():
    if request.method == "POST":
        url = request.form.get("url")
        unique_id = get_unique_id()
        
        add = Link(
        original_url = url,
        short_url = unique_id
        )
        db.session.add(add)
        db.session.commit()
        short_url = unique_id
        return redirect(url_for("route.url",short_url = short_url))
    return render_template("index.jinja")

@bitpy.route("/url/<short_url>")
def url(short_url):
    return render_template("url.jinja",short_url = short_url)


@bitpy.route("/<unique_id>")
def get_url(unique_id):
    link = Link.query.filter_by(short_url = unique_id).first_or_404()
    return redirect(link.original_url)    

web/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BitPy</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
</head>

<body>
    <div class="container" style="padding-top:25px">
        <hgroup>
            <h5>
                BitPy
            </h5>
            <span>Open source url shortener made using flask</span>
        </hgroup>
        <form method="post" action="">
            <input type="url" required minlength="1" name="url" placeholder="input your url"/>
            <button type="submit">Convert</button>
        </form>
  	</div>
  </body>
</html>

web/templates/index.jinja
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BitPy</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
</head>

<body>
    <div class="container" style="padding-top:25px">
        <hgroup>
            <h5>
                BitPy
            </h5>
            <span>Open source url shortener made using flask</span>
        </hgroup>
        <form method="post" action="">
            <input type="url" required minlength="1" name="url" placeholder="input your url"/>
            <button type="submit">Convert</button>
        </form>
  	</div>
  </body>
</html>

web/templates/url.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BitPy</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <style>
    	button{
    		width:40%
    	}
    	a{
    		max-width:100%
    	}
    </style>
</head>

<body>
    <div class="container" style="padding-top:25px">
        <hgroup>
            <h5>
                BitPy
            </h5>
            <span>Open source url shortener made using flask</span>
        </hgroup>
        <article>
	        <a href="{{url_for("route.index")}}" style="dipsplay:block">
	           <p> 
	           	add new url
	           </p> 
	        </a>
	        {% if short_url %}
	        	Shortened url : 
		        <a href="{{config.HOST}}{{short_url}}" target="_blank" id="url"> 
					{{config.HOST}}{{short_url}}
				<a> 
				<button onclick="copy()">
					copy
				</button>
        <script>
        	function copy() {
        	  /* Get the text field */
        	  var copyText = document.getElementById("url");
        	  console.log(copyText.text)
        	
        	  /* Select the text field */

        	  navigator.clipboard.writeText(copyText.text.trim());
        	
        	} 
        </script>
			{% endif %}
        </article>
  	</div>
  </body>
</html>

web/templates/url.jinja
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BitPy</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <style>
    	button{
    		width:40%
    	}
    	a{
    		max-width:100%
    	}
    </style>
</head>

<body>
    <div class="container" style="padding-top:25px">
        <hgroup>
            <h5>
                BitPy
            </h5>
            <span>Open source url shortener made using flask</span>
        </hgroup>
        <article>
	        <a href="{{url_for("route.index")}}" style="dipsplay:block">
	           <p> 
	           	add new url
	           </p> 
	        </a>
	        {% if short_url %}
	        	Shortened url : 
		        <a href="{{config.HOST}}{{short_url}}" target="_blank" id="url"> 
					{{config.HOST}}{{short_url}}
				<a> 
				<button onclick="copy()">
					copy
				</button>
        <script>
        	function copy() {
        	  /* Get the text field */
        	  var copyText = document.getElementById("url");
        	  console.log(copyText.text)
        	
        	  /* Select the text field */

        	  navigator.clipboard.writeText(copyText.text.trim());
        	
        	} 
        </script>
			{% endif %}
        </article>
  	</div>
  </body>
</html>